language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - public
    - .cache
script:
  - yarn build # Générer des fichiers HTML statiques

deploy:
  provider: pages
  skip-cleanup: true
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Conserve les anciens fichiers/constructions des déploiements précédents
  keep-history: true
  on:
    # Quelle branche déclenchera le déploiement
    branch: master
